document.writeln("            <div>");
document.writeln("                <h4 class=\"fst-italic\">Most Recent Posts</h4>");
document.writeln("                <ul class=\"list-unstyled\">");
document.writeln("                    <li>");
document.writeln("                        <a class=\"d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top\" href=\"AI Dog Article.html\">");
document.writeln("                            <img src=\"../../images/Waltuh.webp\" width=\"35%\" height=\"35%\">");
document.writeln("                            <div class=\"col-lg-8\">");
document.writeln("                            <h6 class=\"mb-0\">All About Dogs, An Ai Generated Essay</h6>");
document.writeln("                            <small class=\"text-body-secondary\">March 5th, 2024</small>");
document.writeln("                            </div>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                      <a class=\"d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top\" href=\"AI Caracal Article.html\">");
document.writeln("                        <img src=\"../../images/BigFloppa.webp\" width=\"35%\" height=\"35%\">");
document.writeln("                        <div class=\"col-lg-8\">");
document.writeln("                          <h6 class=\"mb-0\">The Big Floppa</h6>");
document.writeln("                          <small class=\"text-body-secondary\">March 5th, 2024</small>");
document.writeln("                        </div>");
document.writeln("                      </a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a class=\"d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top\" href=\"#\">");
document.writeln("                            <svg class=\"bd-placeholder-img\" width=\"35%\" height=\"35%\" xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\"><rect width=\"100%\" height=\"100%\" fill=\"#777\"></rect></svg>");
document.writeln("                            <div class=\"col-lg-8\">");
document.writeln("                            <h6 class=\"mb-0\">Longer Blog-Full post title: This one has multiple lines!</h6>");
document.writeln("                            <small class=\"text-body-secondary\">January 13, 2024</small>");
document.writeln("                            </div>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("    ");